<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;

class ProductSeeder extends Seeder
{
    public function run(): void
    {
        $restaurantId = DB::table('restaurants')->first()->id;

        $beveragesId = DB::table('families')->where('name', 'Refrescos')->first()->id;
        $appetizersId = DB::table('families')->where('name', 'Entrantes')->first()->id;
        $mainCoursesId = DB::table('families')->where('name', 'Platos Principales')->first()->id;
        $alcoholicBeveragesId = DB::table('families')->where('name', 'Bebidas Alcohólicas')->first()->id;
        $cafesId = DB::table('families')->where('name', 'Cafés')->first()->id;

        $tax21Id = DB::table('taxes')->where('percentage', 21)->first()->id;

        DB::table('products')->insert([
            [
                'uuid' => Str::uuid()->toString(),
                'restaurant_id' => $restaurantId,
                'family_id' => $beveragesId,
                'tax_id' => $tax21Id,
                'name' => 'Coca-Cola',
                'price' => 350,
                'stock' => 100,
                'image_src' => 'http://localhost:4200/assets/products/cocacola.jpeg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'uuid' => Str::uuid()->toString(),
                'restaurant_id' => $restaurantId,
                'family_id' => $beveragesId,
                'tax_id' => $tax21Id,
                'name' => 'Coca-Cola Zero',
                'price' => 350,
                'stock' => 100,
                'image_src' => 'http://localhost:4200/assets/products/cocacolazero.jpeg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'uuid' => Str::uuid()->toString(),
                'restaurant_id' => $restaurantId,
                'family_id' => $beveragesId,
                'tax_id' => $tax21Id,
                'name' => 'Fanta Naranja',
                'price' => 300,
                'stock' => 100,
                'image_src' => 'http://localhost:4200/assets/products/fantanaranja.jpeg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'uuid' => Str::uuid()->toString(),
                'restaurant_id' => $restaurantId,
                'family_id' => $beveragesId,
                'tax_id' => $tax21Id,
                'name' => 'Fanta Limón',
                'price' => 300,
                'stock' => 100,
                'image_src' => 'http://localhost:4200/assets/products/fantalimon.jpeg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'uuid' => Str::uuid()->toString(),
                'restaurant_id' => $restaurantId,
                'family_id' => $beveragesId,
                'tax_id' => $tax21Id,
                'name' => 'Aquarius Limón',
                'price' => 320,
                'stock' => 100,
                'image_src' => 'http://localhost:4200/assets/products/aquariuslimon.jpeg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'uuid' => Str::uuid()->toString(),
                'restaurant_id' => $restaurantId,
                'family_id' => $beveragesId,
                'tax_id' => $tax21Id,
                'name' => 'Aquarius Naranja',
                'price' => 320,
                'stock' => 100,
                'image_src' => 'http://localhost:4200/assets/products/aquariusnaranja.jpeg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'uuid' => Str::uuid()->toString(),
                'restaurant_id' => $restaurantId,
                'family_id' => $beveragesId,
                'tax_id' => $tax21Id,
                'name' => 'Nestea',
                'price' => 320,
                'stock' => 100,
                'image_src' => 'http://localhost:4200/assets/products/nestea.jpeg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'uuid' => Str::uuid()->toString(),
                'restaurant_id' => $restaurantId,
                'family_id' => $beveragesId,
                'tax_id' => $tax21Id,
                'name' => 'Zumo de naranja',
                'price' => 280,
                'stock' => 80,
                'image_src' => 'http://localhost:4200/assets/products/zumonaranja.jpeg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'uuid' => Str::uuid()->toString(),
                'restaurant_id' => $restaurantId,
                'family_id' => $beveragesId,
                'tax_id' => $tax21Id,
                'name' => 'Agua',
                'price' => 200,
                'stock' => 200,
                'image_src' => 'http://localhost:4200/assets/products/agua.jpeg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'uuid' => Str::uuid()->toString(),
                'restaurant_id' => $restaurantId,
                'family_id' => $alcoholicBeveragesId,
                'tax_id' => $tax21Id,
                'name' => 'Estrella Galicia 0,0',
                'price' => 400,
                'stock' => 300,
                'image_src' => 'http://localhost:4200/assets/products/estrellagalicia00.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'uuid' => Str::uuid()->toString(),
                'restaurant_id' => $restaurantId,
                'family_id' => $alcoholicBeveragesId,
                'tax_id' => $tax21Id,
                'name' => 'Estrella Galicia',
                'price' => 400,
                'stock' => 200,
                'image_src' => 'http://localhost:4200/assets/products/estrellagalicia.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'uuid' => Str::uuid()->toString(),
                'restaurant_id' => $restaurantId,
                'family_id' => $alcoholicBeveragesId,
                'tax_id' => $tax21Id,
                'name' => 'Paulaner',
                'price' => 500,
                'stock' => 100,
                'image_src' => 'http://localhost:4200/assets/products/paulaner.jpeg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'uuid' => Str::uuid()->toString(),
                'restaurant_id' => $restaurantId,
                'family_id' => $alcoholicBeveragesId,
                'tax_id' => $tax21Id,
                'name' => 'Mahou',
                'price' => 350,
                'stock' => 100,
                'image_src' => 'http://localhost:4200/assets/products/mahou.jpeg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'uuid' => Str::uuid()->toString(),
                'restaurant_id' => $restaurantId,
                'family_id' => $alcoholicBeveragesId,
                'tax_id' => $tax21Id,
                'name' => 'Heineken',
                'price' => 400,
                'stock' => 100,
                'image_src' => 'http://localhost:4200/assets/products/heineken.jpeg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'uuid' => Str::uuid()->toString(),
                'restaurant_id' => $restaurantId,
                'family_id' => $alcoholicBeveragesId,
                'tax_id' => $tax21Id,
                'name' => 'Radler',
                'price' => 400,
                'stock' => 100,
                'image_src' => 'http://localhost:4200/assets/products/radler.jpeg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'uuid' => Str::uuid()->toString(),
                'restaurant_id' => $restaurantId,
                'family_id' => $cafesId,
                'tax_id' => $tax21Id,
                'name' => 'Café con leche',
                'price' => 200,
                'stock' => 999,
                'image_src' => 'http://localhost:4200/assets/products/cafeconleche.jpeg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'uuid' => Str::uuid()->toString(),
                'restaurant_id' => $restaurantId,
                'family_id' => $cafesId,
                'tax_id' => $tax21Id,
                'name' => 'Café solo',
                'price' => 150,
                'stock' => 999,
                'image_src' => 'http://localhost:4200/assets/products/cafesolo.jpeg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'uuid' => Str::uuid()->toString(),
                'restaurant_id' => $restaurantId,
                'family_id' => $cafesId,
                'tax_id' => $tax21Id,
                'name' => 'Café bombón',
                'price' => 220,
                'stock' => 999,
                'image_src' => 'http://localhost:4200/assets/products/cafebonbon.jpeg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'uuid' => Str::uuid()->toString(),
                'restaurant_id' => $restaurantId,
                'family_id' => $cafesId,
                'tax_id' => $tax21Id,
                'name' => 'Capuchino',
                'price' => 150,
                'stock' => 999,
                'image_src' => 'http://localhost:4200/assets/products/capuchino.jpeg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'uuid' => Str::uuid()->toString(),
                'restaurant_id' => $restaurantId,
                'family_id' => $appetizersId,
                'tax_id' => $tax21Id,
                'name' => 'Bravas',
                'price' => 800,
                'stock' => 80,
                'image_src' => 'http://localhost:4200/assets/products/bravas.jpeg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'uuid' => Str::uuid()->toString(),
                'restaurant_id' => $restaurantId,
                'family_id' => $appetizersId,
                'tax_id' => $tax21Id,
                'name' => 'Calamares',
                'price' => 1300,
                'stock' => 80,
                'image_src' => 'http://localhost:4200/assets/products/calamares.jpeg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'uuid' => Str::uuid()->toString(),
                'restaurant_id' => $restaurantId,
                'family_id' => $appetizersId,
                'tax_id' => $tax21Id,
                'name' => 'chipirones',
                'price' => 1600,
                'stock' => 80,
                'image_src' => 'http://localhost:4200/assets/products/chipirones.jpeg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'uuid' => Str::uuid()->toString(),
                'restaurant_id' => $restaurantId,
                'family_id' => $appetizersId,
                'tax_id' => $tax21Id,
                'name' => 'Torreznos',
                'price' => 400,
                'stock' => 80,
                'image_src' => 'http://localhost:4200/assets/products/torreznos.jpeg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'uuid' => Str::uuid()->toString(),
                'restaurant_id' => $restaurantId,
                'family_id' => $appetizersId,
                'tax_id' => $tax21Id,
                'name' => 'Huevos rotos con jamón',
                'price' => 800,
                'stock' => 80,
                'image_src' => 'http://localhost:4200/assets/products/huevosrotosjamon.jpeg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'uuid' => Str::uuid()->toString(),
                'restaurant_id' => $restaurantId,
                'family_id' => $appetizersId,
                'tax_id' => $tax21Id,
                'name' => 'Tequeños',
                'price' => 800,
                'stock' => 80,
                'image_src' => 'http://localhost:4200/assets/products/tequenos.jpeg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'uuid' => Str::uuid()->toString(),
                'restaurant_id' => $restaurantId,
                'family_id' => $appetizersId,
                'tax_id' => $tax21Id,
                'name' => 'Nachos mexicanos',
                'price' => 800,
                'stock' => 80,
                'image_src' => 'http://localhost:4200/assets/products/nachos.jpeg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'uuid' => Str::uuid()->toString(),
                'restaurant_id' => $restaurantId,
                'family_id' => $appetizersId,
                'tax_id' => $tax21Id,
                'name' => 'Tacos de carne',
                'price' => 800,
                'stock' => 80,
                'image_src' => 'http://localhost:4200/assets/products/tacos.jpeg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'uuid' => Str::uuid()->toString(),
                'restaurant_id' => $restaurantId,
                'family_id' => $appetizersId,
                'tax_id' => $tax21Id,
                'name' => 'Croqueta de jamón (4 Und)',
                'price' => 800,
                'stock' => 80,
                'image_src' => 'http://localhost:4200/assets/products/croquetajamon.jpeg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'uuid' => Str::uuid()->toString(),
                'restaurant_id' => $restaurantId,
                'family_id' => $appetizersId,
                'tax_id' => $tax21Id,
                'name' => 'Croqueta de carrillera (4 Und) ',
                'price' => 800,
                'stock' => 80,
                'image_src' => 'http://localhost:4200/assets/products/croquetacarrillera.jpeg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'uuid' => Str::uuid()->toString(),
                'restaurant_id' => $restaurantId,
                'family_id' => $appetizersId,
                'tax_id' => $tax21Id,
                'name' => 'Croquetas Variadas (4 Und) ',
                'price' => 800,
                'stock' => 80,
                'image_src' => 'http://localhost:4200/assets/products/croquetasvariadas.jpeg',
                'created_at' => now(),
                'updated_at' => now(),
            ],


            [
                'uuid' => Str::uuid()->toString(),
                'restaurant_id' => $restaurantId,
                'family_id' => $appetizersId,
                'tax_id' => $tax21Id,
                'name' => 'Tabla de queso y jamón',
                'price' => 1800,
                'stock' => 80,
                'image_src' => 'http://localhost:4200/assets/products/tablaquesoyjamon.jpeg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'uuid' => Str::uuid()->toString(),
                'restaurant_id' => $restaurantId,
                'family_id' => $mainCoursesId,
                'tax_id' => $tax21Id,
                'name' => 'Paella valenciana (Precio por personas)',
                'price' => 180,
                'stock' => 60,
                'image_src' => 'http://localhost:4200/assets/products/paella.jpeg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'uuid' => Str::uuid()->toString(),
                'restaurant_id' => $restaurantId,
                'family_id' => $mainCoursesId,
                'tax_id' => $tax21Id,
                'name' => 'Arroz al senyoret (Precio por personas)',
                'price' => 190,
                'stock' => 60,
                'image_src' => 'http://localhost:4200/assets/products/arrozsenyoret.jpeg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'uuid' => Str::uuid()->toString(),
                'restaurant_id' => $restaurantId,
                'family_id' => $mainCoursesId,
                'tax_id' => $tax21Id,
                'name' => 'Arroz de secreto y setas (Precio por personas)',
                'price' => 190,
                'stock' => 60,
                'image_src' => 'http://localhost:4200/assets/products/arrozsecreto.jpeg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'uuid' => Str::uuid()->toString(),
                'restaurant_id' => $restaurantId,
                'family_id' => $mainCoursesId,
                'tax_id' => $tax21Id,
                'name' => 'Arroz de boletus y foie (Precio por personas)',
                'price' => 220,
                'stock' => 60,
                'image_src' => 'http://localhost:4200/assets/products/arrozboletus.jpeg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'uuid' => Str::uuid()->toString(),
                'restaurant_id' => $restaurantId,
                'family_id' => $mainCoursesId,
                'tax_id' => $tax21Id,
                'name' => 'Arroz meloso de bogavante (Precio por personas)',
                'price' => 240,
                'stock' => 60,
                'image_src' => 'http://localhost:4200/assets/products/arrozbogavante.jpeg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'uuid' => Str::uuid()->toString(),
                'restaurant_id' => $restaurantId,
                'family_id' => $mainCoursesId,
                'tax_id' => $tax21Id,
                'name' => 'Burger queso de cabra y cebolla caramelizada',
                'price' => 120,
                'stock' => 60,
                'image_src' => 'http://localhost:4200/assets/products/burgercabra.jpeg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'uuid' => Str::uuid()->toString(),
                'restaurant_id' => $restaurantId,
                'family_id' => $mainCoursesId,
                'tax_id' => $tax21Id,
                'name' => 'Burger pollo',
                'price' => 110,
                'stock' => 60,
                'image_src' => 'http://localhost:4200/assets/products/burgerpollo.jpeg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'uuid' => Str::uuid()->toString(),
                'restaurant_id' => $restaurantId,
                'family_id' => $mainCoursesId,
                'tax_id' => $tax21Id,
                'name' => 'Burger',
                'price' => 120,
                'stock' => 60,
                'image_src' => 'http://localhost:4200/assets/products/burger.jpeg',
                'created_at' => now(),
                'updated_at' => now(),
            ],

        ]);
    }
}
